// Single icon family across the product (rule: icon-style-consistent).
// Stroke 1.75 by default for a softer, premium feel; size via tokens.
import {
  Anchor,
  ArrowRight,
  ArrowUpRight,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  CreditCard,
  Eye,
  EyeOff,
  Globe,
  LifeBuoy,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Phone,
  Plus,
  QrCode,
  Search,
  Shield,
  Ship,
  Star,
  Sun,
  Sunrise,
  Ticket,
  TrendingUp,
  User,
  Users,
  Waves,
  X,
} from "lucide-react";

export const I = {
  anchor: Anchor,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clock: Clock,
  card: CreditCard,
  eye: Eye,
  eyeOff: EyeOff,
  globe: Globe,
  lifebuoy: LifeBuoy,
  loader: Loader2,
  logout: LogOut,
  mail: Mail,
  pin: MapPin,
  menu: Menu,
  message: MessageCircle,
  minus: Minus,
  phone: Phone,
  plus: Plus,
  qr: QrCode,
  search: Search,
  shield: Shield,
  ship: Ship,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  ticket: Ticket,
  trending: TrendingUp,
  user: User,
  users: Users,
  waves: Waves,
  close: X,
};

export type IconName = keyof typeof I;

// Token sizes (rule: consistent-icon-sizing)
export const ICON_SIZE = { sm: 14, md: 18, lg: 22, xl: 28 } as const;
